### ISSUE TITLE
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

### ISSUE THREAD

**Issue by Nakilon** [andrius/alpine-ruby#3]
I changed the first line of my Dockerfile:
```
# FROM ruby:2.6-alpine
FROM andrius/alpine-ruby
```
and got the:
```none
	ERROR: Failed to build gem native extension.

    current directory: /usr/lib/ruby/gems/2.6.0/gems/ffi-1.12.1/ext/ffi_c
/usr/bin/ruby -I /usr/lib/ruby/2.6.0 -r ./siteconf20200127-21910-153xr50.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

You might have to install separate package for the ruby development
environment, ruby-dev or ruby-devel for example.

extconf failed, exit code 1

Gem files will remain installed in /usr/lib/ruby/gems/2.6.0/gems/ffi-1.12.1 for inspection.
Results logged to /usr/lib/ruby/gems/2.6.0/extensions/x86_64-linux/2.6.0/ffi-1.12.1/gem_make.out
```
during the `gem install` command that installs my gem that depends on others that include building native extensions. Is this by design? Will having the Ruby sources increase the container size a lot?

**Comment by andrius** [comment]
Yes, I recommend to install build and *dev dependences during docker build and remove them after, they will increase size a lot (for development purposes you might just add them in Dockerfile and never remove). I will update with some samples later

**Comment by Nakilon** [comment]
Hmmm... I wonder if it's possible to compile the gem under `ruby:2.7-alpine` and copy it installed to container based on `andrius/alpine-ruby`.

**Comment by Nakilon** [comment]
Alright, I see, your README already mentions `ruby-dev`.
```none
-    apk add --no-cache --virtual ffi-dependencies build-base libffi-dev && gem install ... && apk del --purge ffi-dependencies
+    apk add --no-cache --virtual ffi-dependencies build-base libffi-dev ruby-dev && gem install ... && apk del --purge ffi-dependencies
```
```none
$ docker run --rm demo1 du -sh /
196.4M	/
$ docker run --rm demo2 du -sh /
172.2M	/
```
Unfortunately it's only -1/8 in my case.
Thank you for quick response anyway.
